### ISSUE TITLE
自定义menu可以是文章展示页面吗

### ISSUE THREAD

**Issue by ShaoxunZeng** [xzhih/hexo-theme-casper#17]
如果是用 ```hexo new page xxx``` 的话只能生成一个页面(直接展示了页面内容)
有办法生成像archives那样多个文章一组的展示页面吗
我看了代码还是不明白如何改

**Comment by ShaoxunZeng** [comment]
我现在唯一想到的办法就是修改nav的代码，在menu里添加catagory的内容
就是把分类的标签作为memu的一个选项来展示，这样等于把catagories搬到nav上面来了

**Comment by xzhih** [comment]
不用改代码，直接在 config 里添加分类对应的路径就可以了

**Comment by ShaoxunZeng** [comment]
config配置指的是
```
menu:
  ABOUT: /about
  ARCHIVES: /archives
  TEST: /test
```
这样吗，但是这样好像就是单独的一个页面，不会像首页一样有多个card展示页

**Comment by xzhih** [comment]
```yaml
menu:
  ABOUT: /about
  ARCHIVES: /archives
  TEST: /categories/test/
```
